name: "Build and push Dadosfera's images to dockerhub"
on:
  workflow_call:
    inputs:
      image-directory:
        required: true
        type: string
      dockerhub-username:
        required: true
        type: string
      image-name:
        required: true
        type: string
      readme-filepath:
        required: true
        type: string
    secrets:
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get image version
        id: image_version
        run: echo "::set-output name=version::$(cat ${{ inputs.image-directory }}/VERSION)"

      - name: Build and push image
        env:
          TAG: ${{ steps.image_version.outputs.version }}
          BUILD_DIRECTORY: ./${{ inputs.image-directory }}
          IMAGE_NAME: ${{ inputs.image-name }}
        run: |
          docker build -t ${IMAGE_NAME} -f ${BUILD_DIRECTORY}/Dockerfile .
          docker tag ${IMAGE_NAME} dadosfera/${IMAGE_NAME}:${TAG}
          docker push dadosfera/${IMAGE_NAME}:${TAG}

      - name: Push README files to DockerHub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        env:
          DOCKERHUB_REPOSITORY: dadosfera/${{ inputs.image-name }}
          README_FILEPATH: ${{ inputs.readme-filepath }}
