name: Release
on:
  push:
    branches:
      - main
jobs:
  semantic_release:
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ (steps.semantic.outputs.new_release_published == 'true' && steps.semantic.outputs.new_release_version) || (github.event_name == 'workflow_dispatch' && '0.0.0') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - if: github.event_name != 'workflow_dispatch'
        name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19
          extra_plugins: |
            conventional-changelog-eslint
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
